Vagrant.configure("2") do |config|
    # on utise vagrant, mais il faudra passer par terraform

    config.vm.define "vm1" do |vm|
        vm.vm.box = "debian/bullseye64"
        vm.vm.hostname = "debian-vm1"
        vm.vm.synced_folder ".", "/vagrant", type: "rsync"
        vm.vm.network "private_network", ip: "192.168.56.11"

        vm.vm.provider "virtualbox" do |vb|
            vb.name = "debian-vm1"
            vb.memory = 1024
            vb.cpus = 1
        end

        # Provision shell initial
        vm.vm.provision "shell", inline: <<-SHELL
            apt-get update -y
            apt-get install -y ansible python3 python3-pip

            # 🔧 Install globally for all users
            python3 -m pip install --upgrade pip
            python3 -m pip install requests
        SHELL

        vm.vm.provision "ansible" do |ansible|
            ansible.playbook = "playbook.yml"
            ansible.inventory_path = "inventory"
            ansible.limit = "vm1"
            ansible.extra_vars = {
                ansible_user: "vagrant"
            }
        end
    end
end
