Vagrant.configure("2") do |config|
    # on utise vagrant, mais il faudra passer par terraform

    (1..2).each do |i|
        config.vm.define "vm#{i}" do |vm|
            vm.vm.box = "generic/alma9"
            # vm.vm.box_version = "9.6.20240619"
            vm.vm.hostname = "alma-vm#{i}"
            vm.vm.synced_folder ".", "/vagrant", type: "rsync"
            vm.vm.network "private_network", ip: "192.168.56.#{10 + i}"
            # Forcer la redirection SSH : port 2221+i pour chaque VM
            vm.vm.network "forwarded_port", guest: 22, host: 2221 + i, id: "ssh"

            vm.vm.provider "virtualbox" do |vb|
                vb.name = "alma-vm#{i}"
                vb.memory = 1024
                vb.cpus = 1
            end

            # Provision shell initial
            vm.vm.provision "shell", inline: <<-SHELL
                dnf install -y epel-release
                dnf update -y
                dnf install -y ansible
                dnf install -y ansible python3 python3-pip

                # 🔧 Install globally for all users
                python3 -m pip install --upgrade pip
                python3 -m pip install requests
            SHELL

            vm.vm.provision "ansible" do |ansible|
                ansible.playbook = "playbook.yml"
                ansible.inventory_path = "inventory"
                ansible.limit = "vm#{i}"
                ansible.extra_vars = {
                    ansible_user: "vagrant"
                }
            end
        end
    end
end
